name: Daily Netlify build trigger

on:
  schedule:
    # Runs at 5:50 AM UTC every day
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request to Netlify's build hook
        env:
          NETLIFY_DAILY_BUILD_HOOK: ${{ secrets.NETLIFY_DAILY_BUILD_HOOK }}
        run: |
          curl -X POST -d {} "$NETLIFY_DAILY_BUILD_HOOK"